# Generated by Django 4.2.28 on 2026-04-07 21:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanevento',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='scanevento',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída / Venda / Consumo')], max_length=10, verbose_name='Tipo de Movimentação')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('motivo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivo / Justificativa')),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Movimentação')),
                ('lote_vinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='tracker.lotedevinho')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-data_movimentacao'],
            },
        ),
    ]
