# Generated by Django 5.1.4 on 2025-05-31 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotedevinho',
            name='dicas_armazenamento',
            field=models.TextField(blank=True, help_text='Dicas para armazenar o vinho corretamente.', null=True),
        ),
        migrations.AddField(
            model_name='lotedevinho',
            name='harmonizacao',
            field=models.TextField(blank=True, help_text='Sugestões de harmonização com alimentos.', null=True),
        ),
        migrations.AddField(
            model_name='lotedevinho',
            name='link_rede_social_vinicola',
            field=models.URLField(blank=True, help_text='Link para a rede social oficial da vinícola.', null=True),
        ),
        migrations.AddField(
            model_name='lotedevinho',
            name='link_video_producao',
            field=models.URLField(blank=True, help_text='Link para um vídeo sobre a produção (YouTube, Vimeo, etc.).', null=True),
        ),
        migrations.AddField(
            model_name='lotedevinho',
            name='temperatura_servico',
            field=models.CharField(blank=True, help_text='Temperatura ideal para servir o vinho.', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='AvaliacaoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrelas', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Pontuação de 1 a 5 estrelas.')),
                ('comentario', models.TextField(blank=True, help_text='Comentário sobre o vinho.', null=True)),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
                ('lote_vinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='tracker.lotedevinho')),
            ],
            options={
                'ordering': ['-data_avaliacao'],
            },
        ),
    ]
