# Generated by Django 5.1.4 on 2025-05-31 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_lotedevinho_dicas_armazenamento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacaocliente',
            old_name='lote_vinho',
            new_name='nome_lote',
        ),
    ]
