# Generated by Django 5.1.4 on 2025-06-05 00:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_lotedevinho_nivel_alerta_estoque_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lotedevinho',
            options={'ordering': ['-data_colheita', '-timestamp_criacao'], 'verbose_name': 'Lote de Vinho', 'verbose_name_plural': 'Lotes de Vinho'},
        ),
        migrations.AddField(
            model_name='avaliacaocliente',
            name='email_avaliador',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Seu Email (Opcional, não será publicado)'),
        ),
        migrations.AddField(
            model_name='avaliacaocliente',
            name='nome_avaliador',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Seu Nome (Opcional)'),
        ),
        migrations.AddField(
            model_name='lotedevinho',
            name='imagem_vinho',
            field=models.ImageField(blank=True, null=True, upload_to='vinhos_imagens/', verbose_name='Imagem do Vinho/Rótulo'),
        ),
        migrations.AddField(
            model_name='lotedevinho',
            name='sugestoes_harmonizacao',
            field=models.TextField(blank=True, help_text='Descreva pratos ou tipos de alimentos que combinam bem com este vinho.', null=True, verbose_name='Sugestões de Harmonização'),
        ),
        migrations.AddField(
            model_name='lotedevinho',
            name='ultima_modificacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Modificação'),
        ),
        migrations.AddField(
            model_name='lotedevinho',
            name='video_url',
            field=models.URLField(blank=True, help_text="Link para um vídeo (Ex: YouTube, Vimeo) sobre o vinho, vinícola ou produção. Use o link de 'incorporar' (embed).", null=True, verbose_name='URL do Vídeo'),
        ),
        migrations.AlterField(
            model_name='lotedevinho',
            name='dicas_armazenamento',
            field=models.TextField(blank=True, help_text='Instruções sobre como armazenar a garrafa para preservar a qualidade do vinho.', null=True, verbose_name='Dicas de Armazenamento'),
        ),
        migrations.AlterField(
            model_name='lotedevinho',
            name='temperatura_servico',
            field=models.CharField(blank=True, help_text='Ex: 16-18°C', max_length=100, null=True, verbose_name='Temperatura Ideal de Serviço'),
        ),
    ]
