# Generated by Django 5.1.4 on 2025-06-05 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_lotedevinho_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacaocliente',
            old_name='nome_lote',
            new_name='lote_vinho',
        ),
        migrations.AddField(
            model_name='lotedevinho',
            name='temperatura_servico_recomendada',
            field=models.CharField(blank=True, help_text='Ex: 16-18°C', max_length=100, null=True, verbose_name='Temperatura Ideal de Serviço'),
        ),
        migrations.AlterField(
            model_name='lotedevinho',
            name='temperatura_servico',
            field=models.CharField(blank=True, help_text='Temperatura ideal para servir o vinho.', max_length=50, null=True),
        ),
    ]
